# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/realm/cmake/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/realm/cmake/source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/realm/cmake/source/CMakeFiles /home/realm/cmake/source/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/realm/cmake/source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named global

# Build rule for target.
global: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 global
.PHONY : global

# fast build rule for target.
global/fast:
	$(MAKE) -f global/CMakeFiles/global.dir/build.make global/CMakeFiles/global.dir/build
.PHONY : global/fast

#=============================================================================
# Target rules for targets named tokenize

# Build rule for target.
tokenize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tokenize
.PHONY : tokenize

# fast build rule for target.
tokenize/fast:
	$(MAKE) -f tokenize/CMakeFiles/tokenize.dir/build.make tokenize/CMakeFiles/tokenize.dir/build
.PHONY : tokenize/fast

#=============================================================================
# Target rules for targets named router

# Build rule for target.
router: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 router
.PHONY : router

# fast build rule for target.
router/fast:
	$(MAKE) -f router/CMakeFiles/router.dir/build.make router/CMakeFiles/router.dir/build
.PHONY : router/fast

#=============================================================================
# Target rules for targets named datamgr

# Build rule for target.
datamgr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datamgr
.PHONY : datamgr

# fast build rule for target.
datamgr/fast:
	$(MAKE) -f datamgr/CMakeFiles/datamgr.dir/build.make datamgr/CMakeFiles/datamgr.dir/build
.PHONY : datamgr/fast

#=============================================================================
# Target rules for targets named updatesrv

# Build rule for target.
updatesrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 updatesrv
.PHONY : updatesrv

# fast build rule for target.
updatesrv/fast:
	$(MAKE) -f updates/CMakeFiles/updatesrv.dir/build.make updates/CMakeFiles/updatesrv.dir/build
.PHONY : updatesrv/fast

#=============================================================================
# Target rules for targets named roommgr

# Build rule for target.
roommgr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roommgr
.PHONY : roommgr

# fast build rule for target.
roommgr/fast:
	$(MAKE) -f roommgr/CMakeFiles/roommgr.dir/build.make roommgr/CMakeFiles/roommgr.dir/build
.PHONY : roommgr/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... global"
	@echo "... tokenize"
	@echo "... router"
	@echo "... datamgr"
	@echo "... updatesrv"
	@echo "... roommgr"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

